server:
  port: 8081

spring:
  application:
    name: eureka-client
    #需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name 。

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/


#服务注册与发现，用于服务的注册与发现，客户端