server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    #通过 eureka.client.registerWithEureka：false 和 fetchRegistry：false 来表明自己是一个eureka server.
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server


#服务注册与发现，用于服务的注册与发现，服务注册服务端